server:
  port: 8081

spring:
  application:
    name: seata-eureka
eureka:
  instance:
    hostname: localhost
  client:
    #registerWithEureka表示是否注册自身到eureka服务器
    register-with-eureka: false
    #fetchRegistry表示是否从eureka服务器获取注册信息。
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

